Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np

def form_array():
    number = int(input('Введите размерность списка: '))
    array = sorted(np.arange(0,number), reverse= True)
    return(array)

form_array()

Введите размерность списка: 7


[6, 5, 4, 3, 2, 1, 0]

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [19]:
def form_matrix():
    number = int(input('Введите размерность матрицы: '))
    array = sorted(np.arange(0,number), reverse= True)
    matrix = np.diag(array, k=0)
    print(matrix)
    sum_ = 0
    for i in range(len(matrix)):
        sum_ += matrix[i][i]
    return(sum_)

form_matrix()

Введите размерность матрицы: 7
[[6 0 0 0 0 0 0]
 [0 5 0 0 0 0 0]
 [0 0 4 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 2 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]]


21

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [25]:
from numpy import linalg
left = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
right = np.array([4, 12, -3])
print(linalg.solve(left,right))
np.allclose( np.dot(left, np.linalg.solve(left, right)), right )

[ 0.46666667  3.84444444 -5.55555556]


True